### ISSUE TITLE
Extract `-test-test` blueprints into their own blueprint-test files

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli-legacy-blueprints#10]
Currently, we have `-test-test` blueprints bundled with their counterpart blueprint tests. For clarity I believe we should keep tests specific to each blueprint in their own files. Though `-test` blueprints are technically a special case (and the `-test-test` name for blueprint tests is a bit awkward), I feel that bundling them with their counterparts makes them less visible, and easier to overlook.

Tests to be extracted:
- [ ] component-test-test
- [ ] controller-test-test
- [ ] helper-test-test
- [ ] initializer-test-test
- [ ] instance-initializer-test-test
- [ ] mixin-test-test
- [ ] route-test-test
- [ ] service-test-test
- [ ] util-test-test
- [ ] view-test-test

@stefanpenner @rwjblue @Turbo87 opinions?

**Comment by Turbo87** [comment]
as mentioned somewhere else already I would keep them in the main blueprint tests for two reasons:

- `-test-test` looks bad...
- they are already tested by the main blueprint tests (e.g. https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/node-tests/blueprints/component-test.js#L25-L35) and having another files just complicates things

we could maybe use another `describe()` block to highlight them better, but I don't see a reason for moving them out of the main test files.
